sudo: required
language: csharp
dist: trusty
mono: none
# dotnet: 2.2.0

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
script: 
  - make build

deploy:
  # deploy master to production
  - provider: script
    script:
      # push docker image to hub, heroku
      # webhook - update the docker image metadata
      make docker-push-master;
      make docker-push-heroku;
      heroku container:release web
    on:
      branch: master